export const GET_ALL_POLICIES = 'GET_ALL_POLICIES';
export const CREATE_POLICY = 'CREATE_POLICY';
export const DELETE_POLICY = 'DELETE_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const LINK_POLICY = 'LINK_POLICY';
export const CLUSTER_WISE_POLICY = 'CLUSTER_WISE_POLICY';

export const GET_ALL_POLICY_TYPES = 'GET_ALL_POLICY_TYPES';
