export const GET_ALL_AUTOTUNEPOLICY = 'GET_ALL_AUTOTUNEPOLICY';
export const CREATE_AUTO_TUNE_POLICY = 'CREATE_AUTO_TUNE_POLICY';
export const UPDATE_AUTO_TUNE_POLICY = 'UPDATE_AUTO_TUNE_POLICY';
export const DELETE_AUTO_TUNE_POLICY = 'DELETE_AUTO_TUNE_POLICY';
