export const GET_ALL_CLUSTERS = 'GET_ALL_CLUSTERS';
export const SET_CLUSTERS = "SET_CLUSTERS";
export const DELETE_CLUSTER_NODE = 'DELETE_CLUSTER_NODE';
export const UPDATE_CLUSTER_NODE = 'UPDATE_CLUSTER_NODE';
export const LINK_CLUSTER_NODE = 'LINK_CLUSTER_NODE';
export const LINK_MULTPLE_NODE_CLUSTER = 'LINK_MULTPLE_NODE_CLUSTER';
